# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[3,4,5],[6,7,8]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.size, a1.ndim

((3,), 3, 1)

In [6]:
# Attributes of 2-dimensional array
a2.shape, a2.size, a2.ndim

((2, 3), 6, 2)

In [7]:
# Attributes of 3-dimensional array
a3.shape, a3.size, a3.ndim

((1, 3, 3), 9, 3)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a1_dataFrame = pd.DataFrame(a1, columns=["Value"])
a1_dataFrame

Value
0      1
1      2
2      3

In [13]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))

In [20]:
# Create an array within a range of 0 and 100 with step 3
array = np.random.randint(0, 100, 3)
array
array_random = np.arange(0, 100, 3)
array_random

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array = np.random.randint(0, 10, size=(7,2))
array

array([[9, 0],
       [8, 6],
       [2, 9],
       [7, 9],
       [8, 1],
       [8, 6],
       [2, 5]])

In [24]:
# Create a radom array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.03714934, 0.4382312 , 0.05762172, 0.73273906, 0.41515415],
       [0.18534559, 0.16269551, 0.21450295, 0.74036674, 0.50518151],
       [0.42794252, 0.77445588, 0.62942304, 0.39850875, 0.94153732]])

In [25]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [26]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(array)

array([1, 2, 3, 4, 5, 7, 9])

In [28]:
# Find the 0'th index of the latest array you created
array[0]
array

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [30]:
# Get the first 2 rows of latest array you created
array[0], array[1]
array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [33]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2,:2]

array([[9, 1],
       [5, 3]])

In [34]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a4 = np.random.randint(10, size=(3, 5))
ones = np.ones((3, 5))

In [35]:
# Add the two arrays together
a4 + ones


array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [36]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5,3))

In [37]:
# Try add the array of ones and the other most recent array together
a4 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [38]:
# Create another array of ones of shape (3, 5)
ones = ones.T

In [39]:
# Subtract the new array of ones from the other most recent array
a4 - ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [40]:
# Multiply the ones array with the latest array
a4 * ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [41]:
# Take the latest array to the power of 2 using '**'
ones**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
# Do the same thing with np.square()
np.square(ones)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
# Find the mean of the latest array using np.mean()
ones.mean()

1.0

In [45]:
# Find the maximum of the latest array using np.max()
ones.max()

1.0

In [46]:
# Find the minimum of the latest array using np.min()
ones.min()

1.0

In [47]:
# Find the standard deviation of the latest array
ones.std()

0.0

In [48]:
# Find the variance of the latest array
ones.var()

0.0

In [51]:
# Reshape the latest array to (3, 5, 1)
ones = ones.reshape(3,5,1)


In [52]:
# Transpose the latest array
ones.T

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

What does the transpose do?

In [55]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array = np.random.randint(0,10)
ones = np.ones((3,3))
ones1 = np.ones((3,2))

In [56]:
# Perform a dot product on the two newest arrays you created
ones.dot(ones1)

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

In [58]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array1 = np.random.randint(0,10, size=(4,3))
array2 = np.random.randint(0,10, size=(4,3))

In [59]:
# Perform a dot product on the two newest arrays you created
array1.dot(array2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [62]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
new_array = array1.T
array2.dot(new_array)

array([[ 92,  80,  74, 112],
       [ 73, 113,  36, 128],
       [ 82, 113,  49, 135],
       [ 61,  57,  42,  72]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [63]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1 = np.random.randint(0,10, size=(3,2))
array2 = np.random.randint(0,10, size=(3,2))

In [64]:
# Compare the two arrays with '>'
array1 > array2

array([[False, False],
       [False,  True],
       [ True,  True]])

What happens when you compare the arrays with `>`?

In [65]:
# Compare the two arrays with '>='
array1 >= array2

array([[False, False],
       [False,  True],
       [ True,  True]])

In [66]:
# Find which elements of the first array are greater than 7
array1 > 7

array([[False, False],
       [False,  True],
       [False,  True]])

In [67]:
# Which parts of each array are equal? (try using '==')
array1 == array2

array([[False, False],
       [False, False],
       [False, False]])

In [68]:
# Sort one of the arrays you just created in ascending order
np.sort(array1)

array([[0, 2],
       [4, 9],
       [6, 9]])

In [69]:
# Sort the indexes of one of the arrays you just created
np.argsort(array1)

array([[1, 0],
       [0, 1],
       [0, 1]])

In [70]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array1)

3

In [71]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array1)

1

In [72]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(array1, axis=1)

array([0, 1, 1])

In [73]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmax(array1, axis=0)

array([2, 1])

In [74]:

# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.17773212, -0.41038331,  1.17971634, -0.89820794,  0.83479542],
       [ 0.29656138, -1.03782988, -0.07580375,  0.97296353,  0.79559546],
       [ 1.49543425,  0.33818125,  3.37229625, -0.92039081, -0.39863839]])

In [76]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(0,100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.